---
name: "Infrastructure"
description: "Infrastructure agent (OpenClaw)"
status: connected
mattermost_channel: "kcy9qd8tyjn59gecnenee1hubo"
mattermost_bot_id: "6ebnaukrkfb88pkfxh5qb9bezo"
mattermost_token: "1u1s4y3wqbbgdquznfrxjh9whe"
port: 18797

tools: []
skills: []
mcps: []
library: []
values: []
---
